const { sequelize, Food } = require('./models/index.js');

const rawData = [
  { category: 'Protein', name: 'Whole Egg', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Egg White', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Egg Yolk', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Boiled Egg', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Scrambled Egg', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Omelette', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Egg Bhurji', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Breast', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Thigh', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Curry', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Grilled Chicken', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Roast', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Fry', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chicken Stew', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Chicken Biryani', size: 1, unit: 'plate' },
  { category: 'Protein', name: 'Sardine (Mathi)', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Mackerel (Ayala)', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Tuna', size: 100, unit: 'g' },
  { category: 'Protein', name: 'King Fish (Neymeen)', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Seer Fish', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Pomfret', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Fish Curry', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Fish Fry', size: 1, unit: 'piece' },
  { category: 'Protein', name: 'Prawns', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Crab', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Beef Curry', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Beef Fry', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Beef Roast', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Beef Stew', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Beef Biryani', size: 1, unit: 'plate' },
  { category: 'Protein', name: 'Mutton Curry', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Mutton Roast', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Mutton Stew', size: 1, unit: 'cup' },
  { category: 'Protein', name: 'Mutton Biryani', size: 1, unit: 'plate' },
  { category: 'Carbohydrate', name: 'White Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Kerala Matta Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Brown Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Basmati Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Jeera Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Ghee Rice', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Fried Rice', size: 1, unit: 'plate' },
  { category: 'Carbohydrate', name: 'Appam', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Puttu', size: 1, unit: 'cylinder' },
  { category: 'Other', name: 'Kadala Curry', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Idiyappam', size: 2, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Pathiri', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Ney Pathiri', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Dosa', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Masala Dosa', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Ghee Dosa', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Set Dosa', size: 2, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Idli', size: 2, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Upma', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Aval Upma', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Rava Upma', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Poori', size: 2, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Chapati', size: 1, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Parotta', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Sambar', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Rasam', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Moru Curry', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Pulissery', size: 1, unit: 'cup' },
  { category: 'Vegetable', name: 'Avial', size: 1, unit: 'cup' },
  { category: 'Vegetable', name: 'Thoran', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Olan', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Kootu Curry', size: 1, unit: 'cup' },
  { category: 'Vegetable', name: 'Erissery', size: 1, unit: 'cup' },
  { category: 'Vegetable', name: 'Mezhukkupuratti', size: 1, unit: 'cup' },
  { category: 'Vegetable', name: 'Carrot', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Beetroot', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Beans', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Broccoli', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Cauliflower', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Cabbage', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Cucumber', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Tomato', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Onion', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Pumpkin', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Bitter Gourd', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Ladies Finger', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Brinjal', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Spinach', size: 100, unit: 'g' },
  { category: 'Vegetable', name: 'Drumstick', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Banana', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Nendran Banana', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Apple', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Orange', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Mango', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Pineapple', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Papaya', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Watermelon', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Grapes', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Guava', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Pomegranate', size: 100, unit: 'g' },
  { category: 'Fruit', name: 'Pear', size: 1, unit: 'medium' },
  { category: 'Fruit', name: 'Kiwi', size: 1, unit: 'piece' },
  { category: 'Dairy', name: 'Milk', size: 250, unit: 'ml' },
  { category: 'Dairy', name: 'Skim Milk', size: 250, unit: 'ml' },
  { category: 'Dairy', name: 'Curd', size: 100, unit: 'g' },
  { category: 'Dairy', name: 'Greek Yogurt', size: 100, unit: 'g' },
  { category: 'Dairy', name: 'Paneer', size: 100, unit: 'g' },
  { category: 'Dairy', name: 'Cheese', size: 1, unit: 'slice' },
  { category: 'Healthy Fat', name: 'Butter', size: 10, unit: 'g' },
  { category: 'Healthy Fat', name: 'Ghee', size: 10, unit: 'g' },
  { category: 'Protein', name: 'Green Gram', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Black Gram', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Chickpeas', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Kidney Beans', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Lentils', size: 100, unit: 'g' },
  { category: 'Protein', name: 'Soy Chunks', size: 100, unit: 'g' },
  { category: 'Healthy Fat', name: 'Almonds', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Cashews', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Walnuts', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Pistachios', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Peanuts', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Pumpkin Seeds', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Sunflower Seeds', size: 30, unit: 'g' },
  { category: 'Healthy Fat', name: 'Chia Seeds', size: 20, unit: 'g' },
  { category: 'Healthy Fat', name: 'Flax Seeds', size: 20, unit: 'g' },
  { category: 'Supplement', name: 'Whey Protein', size: 1, unit: 'scoop' },
  { category: 'Supplement', name: 'Mass Gainer', size: 1, unit: 'scoop' },
  { category: 'Carbohydrate', name: 'Oats', size: 50, unit: 'g' },
  { category: 'Healthy Fat', name: 'Peanut Butter', size: 1, unit: 'tbsp' },
  { category: 'Other', name: 'Peanut Butter Sandwich', size: 2, unit: 'slice' },
  { category: 'Carbohydrate', name: 'Brown Bread', size: 2, unit: 'slice' },
  { category: 'Carbohydrate', name: 'Multigrain Bread', size: 2, unit: 'slice' },
  { category: 'Carbohydrate', name: 'Sweet Potato', size: 100, unit: 'g' },
  { category: 'Carbohydrate', name: 'Boiled Potato', size: 100, unit: 'g' },
  { category: 'Other', name: 'Pazham Pori', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Parippu Vada', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Uzhunnu Vada', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Sukhiyan', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Banana Chips', size: 30, unit: 'g' },
  { category: 'Other', name: 'Sharkara Varatti', size: 30, unit: 'g' },
  { category: 'Other', name: 'Unniyappam', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Kozhukatta', size: 1, unit: 'piece' },
  { category: 'Beverage', name: 'Black Coffee', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Coffee with Milk', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Tea', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Green Tea', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Lemon Juice', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Tender Coconut Water', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Buttermilk', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Orange Juice', size: 250, unit: 'ml' },
  { category: 'Beverage', name: 'Apple Juice', size: 250, unit: 'ml' },
  { category: 'Other', name: 'Payasam', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Palada Payasam', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Ada Pradhaman', size: 1, unit: 'cup' },
  { category: 'Other', name: 'Gulab Jamun', size: 2, unit: 'piece' },
  { category: 'Other', name: 'Laddu', size: 1, unit: 'piece' },
  { category: 'Other', name: 'Halwa', size: 50, unit: 'g' },
  { category: 'Other', name: 'Veg Burger', size: 1, unit: 'burger' },
  { category: 'Other', name: 'Chicken Burger', size: 1, unit: 'burger' },
  { category: 'Other', name: 'Pizza', size: 2, unit: 'slice' },
  { category: 'Other', name: 'French Fries', size: 100, unit: 'g' },
  { category: 'Other', name: 'Shawarma', size: 1, unit: 'roll' },
  { category: 'Other', name: 'Sandwich', size: 1, unit: 'sandwich' },
  { category: 'Other', name: 'Momos', size: 6, unit: 'piece' },
  { category: 'Carbohydrate', name: 'Pongal', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Lemon Rice', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Tamarind Rice', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Curd Rice', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Coconut Rice', size: 1, unit: 'cup' },
  { category: 'Carbohydrate', name: 'Bisibele Bath', size: 1, unit: 'cup' },
];

async function seed() {
  await sequelize.sync({ alter: true });
  console.log('DB Synced. Inserting foods...');

  const foodsToInsert = rawData.map(f => ({
    facilityId: null,
    name: f.name,
    category: f.category,
    servingSize: f.size,
    servingUnit: f.unit,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0
  }));

  try {
    for (const food of foodsToInsert) {
      const exists = await Food.findOne({ where: { name: food.name, facilityId: null } });
      if (!exists) {
        await Food.create(food);
        console.log('Inserted:', food.name);
      }
    }
    console.log('Seed completed successfully!');
  } catch (error) {
    console.error('Seed Error:', error);
  } finally {
    process.exit(0);
  }
}

seed();
